version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/canceen/cache:/config
      - /home/canceen/media:/media    
    restart: 'unless-stopped'
    
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
   
    extra_hosts:
      - "host.docker.internal:host-gateway"
